// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInterfaces(arg1:boolean):Promise<Array<string>>;

export function StartMonitoring(arg1:string):Promise<string>;

export function StartPacketCapture(arg1:string):Promise<string>;

export function StopMonitoring():Promise<void>;

export function StopPacketCapture():Promise<void>;
