// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInterfaces(arg1) {
  return window['go']['main']['App']['GetInterfaces'](arg1);
}

export function StartMonitoring(arg1) {
  return window['go']['main']['App']['StartMonitoring'](arg1);
}

export function StartPacketCapture(arg1) {
  return window['go']['main']['App']['StartPacketCapture'](arg1);
}

export function StopMonitoring() {
  return window['go']['main']['App']['StopMonitoring']();
}

export function StopPacketCapture() {
  return window['go']['main']['App']['StopPacketCapture']();
}
